// Mock doctor data for testing without database
export const MOCK_DOCTORS = [
  // General Medicine
  {
    id: "doc_1",
    clerkUserId: "doctor_general_1",
    email: "dr.rohit.kumar@medcare.com",
    name: "Dr. Rohit Kumar",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=RohitKumar",
    role: "DOCTOR",
    specialty: "General Medicine",
    experience: 15,
    description: "Experienced general physician with expertise in preventive care and chronic disease management. Committed to providing comprehensive healthcare services to all age groups.",
    verificationStatus: "VERIFIED",
  },
  {
    id: "doc_2",
    clerkUserId: "doctor_general_2",
    email: "dr.priya.singh@medcare.com",
    name: "Dr. Priya Singh",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=PriyaSingh",
    role: "DOCTOR",
    specialty: "General Medicine",
    experience: 10,
    description: "Dedicated to patient-centered care with focus on family medicine and wellness programs. Fluent in multiple languages including Hindi, English and Bengali.",
    verificationStatus: "VERIFIED",
  },
  {
    id: "doc_3",
    clerkUserId: "doctor_general_3",
    email: "dr.amit.patel@medcare.com",
    name: "Dr. Amit Patel",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=AmitPatel",
    role: "DOCTOR",
    specialty: "General Medicine",
    experience: 12,
    description: "Specializes in adult medicine, health screenings, and preventive care. Known for thorough examinations and patient education.",
    verificationStatus: "VERIFIED",
  },

  // Cardiology
  {
    id: "doc_4",
    clerkUserId: "doctor_cardio_1",
    email: "dr.abhishek.sharma@medcare.com",
    name: "Dr. Abhishek Sharma",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=AbhishekSharma",
    role: "DOCTOR",
    specialty: "Cardiology",
    experience: 18,
    description: "Board-certified cardiologist specializing in interventional cardiology and heart failure management. Published researcher in cardiovascular medicine with over 50 papers.",
    verificationStatus: "VERIFIED",
  },
  {
    id: "doc_5",
    clerkUserId: "doctor_cardio_2",
    email: "dr.anjali.reddy@medcare.com",
    name: "Dr. Anjali Reddy",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=AnjaliReddy",
    role: "DOCTOR",
    specialty: "Cardiology",
    experience: 14,
    description: "Expert in non-invasive cardiology, echocardiography, and cardiac rehabilitation. Strong focus on preventive cardiology and lifestyle modifications.",
    verificationStatus: "VERIFIED",
  },
  {
    id: "doc_6",
    clerkUserId: "doctor_cardio_3",
    email: "dr.rajesh.gupta@medcare.com",
    name: "Dr. Rajesh Gupta",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=RajeshGupta",
    role: "DOCTOR",
    specialty: "Cardiology",
    experience: 16,
    description: "Specialist in cardiac arrhythmias and pacemaker implantation. Extensive experience in managing complex cardiac conditions.",
    verificationStatus: "VERIFIED",
  },

  // Dermatology
  {
    id: "doc_7",
    clerkUserId: "doctor_derm_1",
    email: "dr.ishan.verma@medcare.com",
    name: "Dr. Ishan Verma",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=IshanVerma",
    role: "DOCTOR",
    specialty: "Dermatology",
    experience: 11,
    description: "Specialist in medical and cosmetic dermatology. Expertise in acne treatment, skin cancer screening, and anti-aging procedures. Uses latest laser technology.",
    verificationStatus: "VERIFIED",
  },
  {
    id: "doc_8",
    clerkUserId: "doctor_derm_2",
    email: "dr.sneha.joshi@medcare.com",
    name: "Dr. Sneha Joshi",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=SnehaJoshi",
    role: "DOCTOR",
    specialty: "Dermatology",
    experience: 9,
    description: "Focus on treating complex skin conditions, eczema, psoriasis, and hair disorders. Uses latest dermatological treatments and therapies.",
    verificationStatus: "VERIFIED",
  },
  {
    id: "doc_9",
    clerkUserId: "doctor_derm_3",
    email: "dr.kuldeep.yadav@medcare.com",
    name: "Dr. Kuldeep Yadav",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=KuldeepYadav",
    role: "DOCTOR",
    specialty: "Dermatology",
    experience: 13,
    description: "Experienced in pediatric and adult dermatology. Specializes in allergic skin conditions, vitiligo treatment, and cosmetic dermatology procedures.",
    verificationStatus: "VERIFIED",
  },

  // Endocrinology
  {
    id: "doc_10",
    clerkUserId: "doctor_endo_1",
    email: "dr.suresh.mehra@medcare.com",
    name: "Dr. Suresh Mehra",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=SureshMehra",
    role: "DOCTOR",
    specialty: "Endocrinology",
    experience: 16,
    description: "Expert in diabetes management, thyroid disorders, and hormonal imbalances. Focuses on comprehensive metabolic health and lifestyle interventions.",
    verificationStatus: "VERIFIED",
  },
  {
    id: "doc_11",
    clerkUserId: "doctor_endo_2",
    email: "dr.pooja.malhotra@medcare.com",
    name: "Dr. Pooja Malhotra",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=PoojaMalhotra",
    role: "DOCTOR",
    specialty: "Endocrinology",
    experience: 12,
    description: "Specializes in diabetes care, obesity management, and osteoporosis. Strong advocate for lifestyle medicine and patient empowerment.",
    verificationStatus: "VERIFIED",
  },
  {
    id: "doc_12",
    clerkUserId: "doctor_endo_3",
    email: "dr.vikas.chauhan@medcare.com",
    name: "Dr. Vikas Chauhan",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=VikasChauhan",
    role: "DOCTOR",
    specialty: "Endocrinology",
    experience: 14,
    description: "Specialist in PCOS, growth disorders, and adrenal conditions. Known for personalized treatment plans and patient education.",
    verificationStatus: "VERIFIED",
  },

  // Gastroenterology
  {
    id: "doc_13",
    clerkUserId: "doctor_gastro_1",
    email: "dr.arun.mishra@medcare.com",
    name: "Dr. Arun Mishra",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=ArunMishra",
    role: "DOCTOR",
    specialty: "Gastroenterology",
    experience: 17,
    description: "Expert in digestive disorders, liver diseases, and endoscopic procedures. Specialized in inflammatory bowel disease management and therapeutic endoscopy.",
    verificationStatus: "VERIFIED",
  },
  {
    id: "doc_14",
    clerkUserId: "doctor_gastro_2",
    email: "dr.kavita.rao@medcare.com",
    name: "Dr. Kavita Rao",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=KavitaRao",
    role: "DOCTOR",
    specialty: "Gastroenterology",
    experience: 13,
    description: "Focus on gastrointestinal motility disorders, acid reflux, and functional GI disorders. Experienced in advanced diagnostic and therapeutic procedures.",
    verificationStatus: "VERIFIED",
  },

  // Neurology
  {
    id: "doc_15",
    clerkUserId: "doctor_neuro_1",
    email: "dr.karan.desai@medcare.com",
    name: "Dr. Karan Desai",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=KaranDesai",
    role: "DOCTOR",
    specialty: "Neurology",
    experience: 15,
    description: "Specialist in treating migraines, epilepsy, and movement disorders. Strong focus on neurological rehabilitation and improving patient quality of life.",
    verificationStatus: "VERIFIED",
  },
  {
    id: "doc_16",
    clerkUserId: "doctor_neuro_2",
    email: "dr.sanjana.bose@medcare.com",
    name: "Dr. Sanjana Bose",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=SanjanaBose",
    role: "DOCTOR",
    specialty: "Neurology",
    experience: 11,
    description: "Expert in stroke care, dementia, and neuromuscular disorders. Uses advanced diagnostic techniques including EMG and nerve conduction studies.",
    verificationStatus: "VERIFIED",
  },
  {
    id: "doc_17",
    clerkUserId: "doctor_neuro_3",
    email: "dr.arjun.kapoor@medcare.com",
    name: "Dr. Arjun Kapoor",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=ArjunKapoor",
    role: "DOCTOR",
    specialty: "Neurology",
    experience: 13,
    description: "Specializes in headache disorders, multiple sclerosis, and peripheral neuropathy. Known for compassionate patient care.",
    verificationStatus: "VERIFIED",
  },

  // Obstetrics & Gynecology
  {
    id: "doc_18",
    clerkUserId: "doctor_obgyn_1",
    email: "dr.meera.iyer@medcare.com",
    name: "Dr. Meera Iyer",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=MeeraIyer",
    role: "DOCTOR",
    specialty: "Obstetrics & Gynecology",
    experience: 14,
    description: "Experienced in high-risk pregnancies, gynecological surgeries, and women's health. Compassionate care for all stages of women's lives.",
    verificationStatus: "VERIFIED",
  },
  {
    id: "doc_19",
    clerkUserId: "doctor_obgyn_2",
    email: "dr.deepa.nair@medcare.com",
    name: "Dr. Deepa Nair",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=DeepaNair",
    role: "DOCTOR",
    specialty: "Obstetrics & Gynecology",
    experience: 16,
    description: "Specialist in prenatal care, fertility treatments, and minimally invasive gynecologic surgery. Focus on holistic women's health and wellness.",
    verificationStatus: "VERIFIED",
  },

  // Oncology
  {
    id: "doc_20",
    clerkUserId: "doctor_onco_1",
    email: "dr.siddharth.banerjee@medcare.com",
    name: "Dr. Siddharth Banerjee",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=SiddharthBanerjee",
    role: "DOCTOR",
    specialty: "Oncology",
    experience: 19,
    description: "Medical oncologist specializing in targeted therapy and immunotherapy. Dedicated to personalized cancer treatment and cutting-edge research.",
    verificationStatus: "VERIFIED",
  },
  {
    id: "doc_21",
    clerkUserId: "doctor_onco_2",
    email: "dr.ritu.shah@medcare.com",
    name: "Dr. Ritu Shah",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=RituShah",
    role: "DOCTOR",
    specialty: "Oncology",
    experience: 15,
    description: "Expert in breast and gynecologic cancers. Comprehensive cancer care with focus on survivorship programs and quality of life.",
    verificationStatus: "VERIFIED",
  },
  {
    id: "doc_22",
    clerkUserId: "doctor_onco_3",
    email: "dr.vikrant.singh@medcare.com",
    name: "Dr. Vikrant Singh",
    imageUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=VikrantSingh",
    role: "DOCTOR",
    specialty: "Oncology",
    experience: 17,
    description: "Specialist in gastrointestinal and lung cancers. Experience in chemotherapy, immunotherapy, and clinical trials.",
    verificationStatus: "VERIFIED",
  },
];

export function getMockDoctorsBySpecialty(specialty) {
  const normalizedSpecialty = specialty.split("%20").join(" ");
  return MOCK_DOCTORS.filter(
    (doctor) =>
      doctor.specialty.toLowerCase() === normalizedSpecialty.toLowerCase()
  );
}

export function getMockDoctorById(id) {
  return MOCK_DOCTORS.find((doctor) => doctor.id === id);
}

export function getAllMockDoctors() {
  return MOCK_DOCTORS;
}
